# Generated by Django 5.0.7 on 2024-07-22 22:39

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationName', models.CharField(max_length=200)),
                ('OrganizationType', models.CharField(max_length=200)),
                ('NumberOfEmployees', models.IntegerField()),
                ('OrganizationEmail', models.EmailField(max_length=254)),
                ('OrganizationPhone', models.CharField(max_length=200)),
                ('OrganizationAddress', models.CharField(max_length=200)),
                ('Registration_Number', models.CharField(max_length=250)),
                ('OrganizationDigitalAddress', models.CharField(max_length=200)),
                ('Organization_City_Of_Operation', models.CharField(max_length=200)),
                ('OrganizationStateOrRegion', models.CharField(max_length=200)),
                ('OrganizationLogo', models.ImageField(upload_to='organization/organization_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('physical_address', models.CharField(max_length=200)),
                ('Digital_address', models.CharField(max_length=200)),
                ('cityOrTown', models.CharField(max_length=200)),
                ('stateOrRegion', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(upload_to='landlord/profile_photos')),
                ('country', django_countries.fields.CountryField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('digita_address', models.CharField(max_length=200)),
                ('mailing_address', models.CharField(max_length=200)),
                ('cityOrTown', models.CharField(max_length=200)),
                ('stateOrRegion', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('num_units', models.IntegerField()),
                ('maintenance_status', models.CharField(max_length=200)),
                ('property_photo', models.ImageField(upload_to='property/property_photos')),
                ('property_video', models.FileField(upload_to='property/property_videos')),
                ('property_amenities', models.TextField()),
                ('property_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_status', models.CharField(max_length=200)),
                ('lease_start_date', models.DateField()),
                ('lease_expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreDashboard.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=200)),
                ('physical_address', models.CharField(max_length=200)),
                ('Digital_address', models.CharField(max_length=200)),
                ('cityOrTown', models.CharField(max_length=200)),
                ('stateOrRegion', models.CharField(max_length=200)),
                ('countryOfOrigin', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreDashboard.property')),
            ],
        ),
    ]
